<?php
/*
Template Name: Optii-Savr Home
*/

$nonce = base64_encode(random_bytes(16));

header(
    "Content-Security-Policy: ".
    "default-src 'none'; ".
    "script-src 'self' https://code.jquery.com https://cdnjs.cloudflare.com 'nonce-$nonce'; ".
    "style-src 'self' https://fonts.googleapis.com 'nonce-$nonce'; ".
    "img-src 'self' data: https://secure.gravatar.com https://optitaxs.com; ".
    "font-src 'self' https://fonts.gstatic.com; ".
    "connect-src 'self' https://optitaxs.com https://*.optitaxs.com; ".
    "frame-src 'self'; ".
    "frame-ancestors 'none'; ".
    "base-uri 'self'; ".
    "object-src 'none'; ".
    "form-action 'self'; ".
    "manifest-src 'self'; ".
    "media-src 'self'; ".
    "worker-src 'self' blob:;"
);
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Optii-Savr | Indirect Tax Saving Evaluator for Manufacturers</title>
    <meta
      name="description"
      content="Explore Optii-Savr — a free tool to evaluate indirect tax-saving schemes like SEZ, MOOWR, EOU, EPCG, and AA before investing in manufacturing in India."
    />
    <meta
      name="keywords"
      content="Indirect Tax, India Manufacturing, Tax Saving Schemes, SEZ, MOOWR, EPCG, AA, EOU, GST, Customs, Optii-Savr"
    />
    <meta name="author" content="Optitax's" />
    <link rel="canonical" href="https://optitaxs.com/optii-savr-user-manual" />
    <link
      rel="shortcut icon"
      href="https://optitaxs.com/wp-content/uploads/2022/06/cropped-favicon-192x192.png"
      type="image/x-icon"
    />
    <link
      rel="stylesheet"
      href="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/css/home.css"
    />
    <!-- Open Graph -->
    <meta
      property="og:title"
      content="Optii-Savr | Evaluate Tax Saving Schemes in India"
    />
    <meta
      property="og:description"
      content="Identify cost-saving opportunities using SEZ, MOOWR, EOU, EPCG, and other schemes. Make informed decisions before investing in manufacturing in India."
    />
    <meta
      property="og:image"
      content="https://optitaxs.com/https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/img/optii-savr-preview.png"
    />
    <meta property="og:url" content="https://optitaxs.com/services/" />
    <meta property="og:type" content="website" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta
      name="twitter:title"
      content="Optii-Savr | Indirect Tax Saving Tool"
    />
    <meta
      name="twitter:description"
      content="Compare schemes like SEZ, MOOWR, EOU, EPCG, AA to determine optimal savings."
    />
    <meta
      name="twitter:image"
      content="https://optitaxs.com/services/https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/img/optii-savr-preview.png"
    />
    <style nonce="<?= $nonce ?>">
</style>
  </head>

  <body>
    <div id="termsModal" class="modal">
      <div class="modal-content">
        <span id="close" class="close">&times;</span>
        <div class="modal-header">Terms of use & disclaimers</div>
        <div class="modal-body">
          <p>
            By visiting this website & this application, you agree to abide by
            the terms of use and disclaimers outlined herein. If you do not
            agree, you must immediately cease using this website. Optii-Savr
            does not collect or save any data uploaded & shared back.
          </p>

          <h3>1. Proprietary Rights</h3>
          <p>
            This website & application and the services available on the website
            are the proprietary property of Optitax's Consulting LLP, a Limited
            Liability Partnership registered in India.
          </p>

          <h3>2. General Terms</h3>
          <p>
            2.1. All materials contained on this website & application are
            protected by applicable copyright and trademark laws. Unauthorized
            use of these materials is strictly prohibited and will be prosecuted
            to the fullest extent of the law.
          </p>
          <p>
            2.2. Optitax's allows the use of this website and its materials on a
            free-of-cost basis to the users
          </p>

          <h3>3. User License</h3>
          <p>
            3.1. This website provides a facility to use the product Optii-Savr
            and other products fully developed by Optitax's.
          </p>
          <p>
            3.2. Permission is granted to print the report generated by this
            evaluator is solely for the purpose of evaluating a business
            proposal. This license is granted free of charge and does not
            constitute a transfer of title. Under this license, you are
            expressly prohibited from:
          </p>
          <ul>
            <li>
              Attempting to copy, decompile, or reverse engineer any software
              contained on Optitax's website & this application;
            </li>
            <li>
              Removing any copyright or other proprietary notations from the
              Optii-Savr;
            </li>
            <li>
              Attempting to access https://optitaxs.com or the Optii-Savr by any
              means other than standard browser applications;
            </li>
            <li>
              Transferring or mirroring https://optitaxs.com or the Optii-Savr
              to another server or website.
            </li>
          </ul>

          <h3>4. Disclaimer</h3>
          <p>
            4.1. The materials, including the Optii-Savr Report on Optitax's
            website, are provided on an 'as is' basis, without any guarantees or
            warranties of any kind.
          </p>
          <p>
            4.2. Optitax's expressly disclaims all warranties, whether express
            or implied, including but not limited to implied warranties of
            merchantability, fitness for a particular purpose, and
            non-infringement of intellectual property rights or other violations
            of rights.
          </p>
          <p>
            4.3. Optitax's makes no representations or warranties regarding the
            accuracy, likely results, or reliability of the use of the materials
            on its website or on any websites linked to this site & this
            application.
          </p>
          <p>
            4.4. Optitax's does not guarantee the correctness, accuracy, or
            reliability of any data uploaded by users on its website & this
            application. Users are solely responsible for the content they
            upload.
          </p>

          <h3>5. Accuracy of materials</h3>
          <p>
            5.1. The materials appearing on https://optitaxs.com or any linked
            sites may include technical, typographical, or photographic errors.
            Optitax's does not warrant that any of the materials are accurate,
            complete, or current.
          </p>
          <p>
            5.2. Optitax's reserves the right to make changes to the materials
            contained on https://optitaxs.com at any time without notice.
            Optitax's does not commit to updating the materials.
          </p>

          <h3>6. Liability</h3>
          <p>
            6.1. Under no circumstances shall Optitax's or its suppliers be
            liable for any damages (including, but not limited to, damages for
            loss of data or profit, or due to business interruption) arising
            from the use or inability to use the materials on Optitax's website
            & this application, even if Optitax's or an authorized
            representative has been notified orally or in writing of the
            possibility of such damages.
          </p>
          <p>
            6.2. Some jurisdictions do not allow limitations on implied
            warranties or the exclusion or limitation of liability for
            consequential or incidental damages; these limitations may not apply
            to you. In such jurisdictions, Optitax's liability is limited to the
            greatest extent permitted by law.
          </p>

          <h3>7. Privacy</h3>
          <p>
            7.1. Optitax's is committed to protecting your privacy. All personal
            information collected through this website & this application will
            be handled in accordance with our Privacy Policy, which complies
            with relevant data protection and privacy laws.
          </p>
          <p>
            7.2. By using this website & this application, you consent to the
            collection, use, and storage of your personal information as
            described in our Privacy Policy.
          </p>

          <h3>8. Governing Law</h3>
          <p>
            8.1. These terms and conditions are governed by and construed in
            accordance with the laws of the State of Maharashtra, India.
          </p>
          <p>
            8.2. Any disputes arising out of or relating to these terms and
            conditions, the use of Optitax's website & this application, or the
            products or services provided shall be resolved exclusively in the
            courts located in Pune, Maharashtra, India. By using this website &
            this application, you agree to submit to the jurisdiction of these
            courts for such purposes.
          </p>

          <h3>9. Severability</h3>
          <p>
            If any provision of these terms is found to be unenforceable or
            invalid, the remaining provisions will continue to be in full force
            and effect.
          </p>

          <h3>10. Entire Agreement</h3>
          <p>
            10.1. These terms constitute the entire agreement between you and
            Optitax's regarding the use of the website, this application and
            supersede all prior agreements and understandings, whether written
            or oral, regarding such use.
          </p>

          <h3>11. Changes to Terms of Use</h3>
          <p>
            Optitax's reserves the right to revise these terms of use at any
            time without notice. By using this website & this application, you
            agree to be bound by the current version of these terms of use.
          </p>

          <p>
            By accessing or using Optitax's website & this application, you
            acknowledge that you have read, understood, and agree to be bound by
            these terms and conditions.
          </p>
          <p class="accept-checkbox">
            <input type="checkbox" id="checkbox" autocomplete="off" />
            <strong style="font-size: 16px">I agree to these terms</strong>
          </p>
        </div>
        <div class="modal-footer">
          <button id="acceptBtn">OK</button>
        </div>
      </div>
    </div>
    <!-- header  -->
    <header>
      <div class="logo-div">
        <img
          id="logo"
          src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/img/logo.png"
          alt="logo"
        />
      </div>
      <div class="title-box">
        <h1 id="title"><em>Optii-Savr</em></h1>
        <p>Compares Customs duty saving schemes & calculates net benefit</p>
      </div>
      <div class="book-div">
        <p id="book-title"><em>From the authors of</em></p>
        <img
          id="book"
          src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/img/books.png"
          alt="books"
        />
      </div>
      <svg
        id="round-svg"
        width="242"
        height="195"
        viewBox="0 0 242 195"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g clip-path="url(#clip0_2308_1199)">
          <path
            d="M164.13 -113.613C169.519 -52.4275 213.903 77.7743 348.322 109.098"
            stroke="url(#paint0_linear_2308_1199)"
          />
          <path
            d="M184.983 -129C190.373 -67.8145 234.757 62.3873 369.175 93.7107"
            stroke="url(#paint1_linear_2308_1199)"
          />
          <path
            d="M148.176 -93.9114C153.565 -32.7259 197.949 97.4759 332.368 128.799"
            stroke="url(#paint2_linear_2308_1199)"
            stroke-opacity="0.9"
          />
          <path
            d="M136.609 -63.3884C141.999 -2.20293 186.383 127.999 320.801 159.322"
            stroke="url(#paint3_linear_2308_1199)"
            stroke-opacity="0.8"
          />
          <path
            d="M109.936 -40.5999C115.326 20.5856 159.709 150.787 294.128 182.111"
            stroke="url(#paint4_linear_2308_1199)"
            stroke-opacity="0.7"
          />
          <path
            d="M78.2593 -20.8242C83.6488 40.3613 128.033 170.563 262.451 201.886"
            stroke="url(#paint5_linear_2308_1199)"
            stroke-opacity="0.6"
          />
          <path
            d="M36.7837 -57C42.1412 24.8191 91.6234 198.457 246.693 238.454"
            stroke="url(#paint6_linear_2308_1199)"
            stroke-opacity="0.5"
          />
        </g>
        <defs>
          <linearGradient
            id="paint0_linear_2308_1199"
            x1="264.356"
            y1="-105.738"
            x2="248.095"
            y2="101.223"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint1_linear_2308_1199"
            x1="285.21"
            y1="-121.125"
            x2="268.949"
            y2="85.8359"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#51586F" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint2_linear_2308_1199"
            x1="248.402"
            y1="-86.0366"
            x2="232.141"
            y2="120.925"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint3_linear_2308_1199"
            x1="236.836"
            y1="-55.5137"
            x2="220.575"
            y2="151.447"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint4_linear_2308_1199"
            x1="210.162"
            y1="-32.7251"
            x2="193.902"
            y2="174.236"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint5_linear_2308_1199"
            x1="178.486"
            y1="-12.9494"
            x2="162.225"
            y2="194.012"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <linearGradient
            id="paint6_linear_2308_1199"
            x1="152.63"
            y1="-47.898"
            x2="130.846"
            y2="229.352"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#1F3576" />
            <stop offset="1" stop-color="#6B6B6B" />
          </linearGradient>
          <clipPath id="clip0_2308_1199">
            <rect width="242" height="195" fill="white" />
          </clipPath>
        </defs>
      </svg>
    </header>
    <!-- Main Section  -->
    <main>
      <h2 id="bg">Background</h2>
      <section>
        <ul>
          <li>
            Cost saving opportunities in Indirect taxes (Customs & GST) need to
            be evaluated before considering investment in India for
            manufacturing of goods (new setup/expansion)
          </li>
          <li>
            Various schemes include Export Oriented Unit (EOU), Duty Drawback
            (All Industry Rate/Brand Rate), Advance Authorisation (AA), Special
            Economic Zone unit (SEZ), Manufacturing in the customs bonded
            warehouse (MOOWR), Export Promotion of Capital Goods (EPCG) & a unit
            in Domestic Tariff Area (DTA)
          </li>
          <li>
            Each of the scheme needs to be evaluated for determining the most
            beneficial scheme in the given circumstances
          </li>
        </ul>
        <div id="learn-more-container">
          <button id="learn-more-btn">Learn more about schemes</button>
          <button id="comparison-of-scheme">Comparison of the schemes</button>
          <button id="learn-more-relevant">
            Explanation of relevant terms
          </button>
        </div>
        <p id="strong-info">
          <strong
            >Optii-Savr helps in calculating the net benefit available while
            opting for the respective scheme over the other schemes
          </strong>
        </p>
        <p>
          This exercise will take approximately 20 minutes and will provide
          essential input for appropriate decision making. In today’s business
          environment, especially the price sensitive markets, cost
          competitiveness, selecting an appropriate scheme can positively impact
          topline and the bottom-line of the business. The tool provides a broad
          level analysis of the same. Optitax's can assist in determining
          precise calculation which may require microlevel information.
        </p>
        <p id="free-msg">
          <strong><i>Optii-Savr is absolutely free</i></strong>
        </p>

        <!-- Pop-up Box -->
        <div id="popup-box" class="popup-box">
          <div class="popup-content">
            <span class="close-btn3">&times;</span>
            <iframe
              src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/reports/Learn more about the Export Promotion Schemes.pdf"
              width="100%"
              height="90%"
            ></iframe>
          </div>
        </div>
        <div id="popup-box2" class="popup-box">
          <div class="popup-content">
            <span class="close-btn32">&times;</span>
            <iframe
              src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/reports/Explanation of relevant terms.pdf"
              width="100%"
              height="90%"
            ></iframe>
          </div>
        </div>
        <div id="popup-box3" class="popup-box">
          <div class="popup-content">
            <span class="close-btn33">&times;</span>
            <iframe
              src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/reports/Scheme comparison.pdf"
              width="100%"
              height="90%"
            ></iframe>
          </div>
        </div>

        <button id="calculate-btn" class="calculate">Next</button>
      </section>
    </main>
    <script nonce="<?= $nonce ?>">
    console.log("Inline JS now allowed!");
</script>
    <script
      src="https://code.jquery.com/jquery-3.6.4.min.js"
      integrity="sha384-UG8ao2jwOWB7/oDdObZc6ItJmwUkR/PfMyt9Qs5AwX7PsnYn1CRKCTWyncPTWvaS"
      crossorigin="anonymous"
    ></script>
    <script src="https://optitaxs.com/wp-content/themes/optitaxtheme/tools/optii-savr/scripts/optii-savr.js"></script>
  </body>
</html>
